### ISSUE TITLE
how to call destructor to load fonts on the fly?

### ISSUE THREAD

**Issue by moebiussurfing** [Kiberchaika/ofxFontStash3#1]
hey @andorxornot,

Thanks for sharing this.
What's the point of your repo vs the other ones from armadillu?

I am trying to destroy the object and create again to free memory and load many fonts on runtime. 
But memory grows as if there were some memory leaks. 
(I tried this repo too and does the same)
I have seen in your commits that have some destructor repair...

That's my code to reload:
```
void ofApp::keyPressed(int k) {
    if (k== ' ')
    {
        fontNormal = ofxFontStash();
        fontNormal.load("Vera.ttf", ofRandom(24, 200));
    }
}
```

I am doing something bad? Any tip?

**Comment by andorxornot** [comment]
@moebiussurfing hi!
i fixed that
thanks for your issue!

**Comment by moebiussurfing** [comment]
thanks @andorxornot !
it works now.

What are the differences between your addon and https://github.com/armadillu/ofxFontStash?

I am asking because I have a project that uses it, and I use several methods of it... 
And I can't replace to yours easily. 

Do you think it could be easy that I copy this destructor to https://github.com/armadillu/ofxFontStash?

**Comment by yeswecan** [comment]
@moebiussurfing hey there! The other ones didn't work on iOS due the way the oF code is written.
